services:
  backend:
    image: backend-hackathon-2026:1.0.0
    build: ./backend
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - hackathon-2026
    ports:
      - 8000:8000

  database:
    image: postgres:16-alpine
    env_file:
      - .env
    networks:
      - hackathon-2026
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: frontend-hackathon-2026:1.0.0
    build: ./frontend
    networks:
      - hackathon-2026
    ports:
      - 8080:8080

volumes:
  postgres_data:
    name: hackathon_postgres_data

networks:
  hackathon-2026:
    external: true
